# Generated by Django 5.0.7 on 2024-07-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена билета')),
                ('logo', models.ImageField(upload_to='media/ticket_logos', verbose_name='Логотип')),
                ('event_date', models.DateTimeField(verbose_name='Дата начало мероприятия')),
                ('duration', models.CharField(max_length=30, verbose_name='Прододжительнось')),
                ('location', models.CharField(max_length=223, verbose_name='Место проведения')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Кол-во билетов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание объекта')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
    ]
